# Generated by Django 5.2.8 on 2025-11-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_pedido_total_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio_en_pedido',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
